### ISSUE TITLE
[Feature] Add option for MM or IA mobs

### ISSUE THREAD

**Issue by fnrcum** [RRS-9747/HeadDrop#13]
It would be nice if we could have some options for plugins like MythicMobs and ItemsAdder mobs such as:

Ignore mobs and don't drop heads for all MM/IA mobs or for specific ones (just as it currently is for normal mobs)
Specify what head to drop for MM/IA mobs in case of custom heads for custom mobs

**Comment by RRS-9747** [comment]
MythicMobs added. Itemadder developer didn't reply me. So it will be delay. As soon as he reply, I will add that too
