### ISSUE TITLE
Placed heads drop permanently

### ISSUE THREAD

**Issue by buerrebones** [RRS-9747/HeadDrop#14]
Really weird bug someone on our server found: if you place a head, break it, then place _any_ other block in the same place, it will _always_ drop that mob head once broken instead. That block is just cursed now. No errors in console, either.

edit: also, your discord link is broken

**Comment by RRS-9747** [comment]
Please update the plugin to latest version

**Comment by buerrebones** [comment]
> Please update the plugin to latest version

We are currently already running version 4.3. If it happens to be a known plugin conflict, we're also running GriefPrevention, Worldguard, Themis, Chunky, McMMO, and FastAsyncWorldEdit on 1.19.

**Comment by ghost** [comment]
I am currently having the same issue, plug-in version 4.3 and a brand new paper download, it even drops it in creative mode when breaking the head or breaking a block in the "cursed" block.

**Comment by RRS-9747** [comment]
Update plugin to 4.4
