### ISSUE TITLE
enderman head dropping?

### ISSUE THREAD

**Issue by tnkv** [RRS-9747/HeadDrop#15]
Hi, using your plugin and disabled the drop of all heads except player's, in the ender world ran into this moment.

https://user-images.githubusercontent.com/67426242/185202604-4a938484-cdcd-45d7-bf37-2d66b55acc7a.mp4

**Comment by tnkv** [comment]
This happened after installing the head from a mob that was killed with the function drop heads from mobs, and after turning off and rebooting the server, installing the old heads leads to this, after placing and removing any block

**Comment by RRS-9747** [comment]
Update your plugin to 4.4
