### ISSUE TITLE
Version 4.16 is infected by malware

### ISSUE THREAD

**Issue by JulianVennen** [RRS-9747/HeadDrop#17]
Hi, I work at Aternos, a large Minecraft server host.
Our systems detected that version 4.16 of your plugin includes malware, which paper announced a while ago: https://forums.papermc.io/threads/malware-announcement.529/

This malware spreads from one jar file to another, e.g. when used in a Minecraft server and also registers system services.

You should delete the version and reinstall the entire system it was built on immediately, and announce an official warning about the problem to the users of your plugin.

If you're reading this as a user of the plugin, I would also recommend to completely reinstall any system you executed the jar file on.

**Comment by RRS-9747** [comment]
Thanks for notifying me.
the affected plugin jar file has been removed from GitHub & Spigot and uploaded a verified fresh plugin jar
