### ISSUE TITLE
Drop chance by permission

### ISSUE THREAD

**Issue by USBCharger** [RRS-9747/HeadDrop#19]
Hey, if you could add drop chances by permission weight (ie: smth like from 1-100) to this plugin, particularly to players that would be really cool, I'd love to move over to this plugin from one I'm using right now since it appears to be abandoned and has some issues.

**Comment by RRS-9747** [comment]
added on 4.22
you can increase the drop chance by 100
the permission node is: "headdrop.chance.*"
replace (*) with 1-100
