### ISSUE TITLE
Headdrops don't happen

### ISSUE THREAD

**Issue by thaboy1992** [RRS-9747/HeadDrop#24]
I installed the latest update but it isn't dropping heads for creepers, zombies, ...

Errors:

[16:26:31] [Server thread/WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.

This error appears when i kill a mob and since the heads aren't dropping, i'm sure its the plugin.

UPDATE:
I'm using Towny and inside a town this is a problem,   in the wilderness,, the heads do drop from pigs, cows, horses, ....
But not from zombie, creeper and skelletons

Please help

**Comment by RRS-9747** [comment]
I think one of your plugins modified vanilla skull items. if you think there is a suck plugin that can modify, please temp remove that & check, let me know the result. I will try to add support for that plugin
