### ISSUE TITLE
Configuration for different mob sounds

### ISSUE THREAD

**Issue by bunnies1230** [RRS-9747/HeadDrop#25]
Hello!
I was wondering if it was possible to have a configuration to change what sounds the heads make when placed on a noteblock?

If I wanted to change the ghast noise from what it is now (entity.ghast.ambient), could do so with something like this?

config.yml:
> GHAST:
  Name: Ghast
  Drop: true
  Chance: 2.5
  Sound: entity.ghast.warn

To be honest, I overlooked this feature til recently, and it works great!

**Comment by RRS-9747** [comment]
Sound is now customizable in the [Premium version](https://www.spigotmc.org/resources/111758/). It may be available on the free version in the next update ;)
