### ISSUE TITLE
the heads fall with almost a 100% chance, but in the config it costs 1%.

### ISSUE THREAD

**Issue by TheRa1nY** [RRS-9747/HeadDrop#33]
when killing mobs, heads fall extremely often, despite the 1% chance in the config. This appeared when switching to 1.21, everything was fine at 1.20.

**Comment by EyesX** [comment]
Can confirm, @ PaperMC 1.21 using HeadDrop 5.2.0

**Comment by RRS-9747** [comment]
Fixed on latest version
